### ISSUE TITLE
Help reproducing/updating icons?

### ISSUE THREAD

**Issue by pedro** [ennoucas/slds-icons-font#1]
Hi there!

First of all, thanks for this project! Super helpful 👌

I'm trying to regenerate the assets you have here with IcoMoon because I just want a subset of them, and also because the font here is triggering a warning in Firefox:

> downloadable font: Glyph bbox was incorrect

I wrote [this script](https://gist.github.com/pedro/2f48f26aac80be87714975c041efb730) to filter svgs out of SLDS, remove their fill and such... But in the end the icons I get from IcoMoon end up smaler than the ones in here. I wonder if you'd be willing to share your approach? Wondering if I need to tweak the svg dimensions or viewport 🤔 

Thank you!

**Comment by pedro** [comment]
ahhhh, think I got it by tweaking the viewport a bit (instead of `0 0 100 100`, moved to `20 20 60 60`; similar ratios for `0 0 1000 1000`).

let me know if any of this sounds good I can open a PR detailing that, and potentially updating the icons. Aside from the Firefox warning, I think some icons may have changed slightly?

**Comment by ennoucas** [comment]
Hi Pedro thanks for the feedback! Feel free to open a PR that would be great!

**Comment by ennoucas** [comment]
@pedro I've updated the repo to generate the font with scripts (not using icomoon anymore). You now have access to both scaled and not scaled fonts. Check you the index.html files in each to see how the icons render. Also updated with latest version of slds icons! Let me know :)

**Comment by pedro** [comment]
Looks great! No glyph warnings in these 👌 

Thank you! ❤️
